<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CMS.Contracts\CMS.Contracts.csproj" />
    <ProjectReference Include="..\CMS.Model\CMS.Model.csproj" />
  </ItemGroup>

</Project>
